In [3]:
import os
os.chdir("C:\\Users\\Dell\\Desktop\\csvfiles")

In [4]:
from glob import glob
files = glob('*.csv');

In [5]:
files

['-03-04-IND_DSR-_04.03.2018_1_.hi.en.csv',
 '-03-06-IND_DSR-_06.03.2018_1_.hi.en.csv',
 '-04-04-IND_DSR-_04.04.2018_1_.hi.en.csv',
 '-04-06-IND_DSR-_06.04.2018.hi.en_1_.csv',
 '018-02-11-IND_DSR-_11.02.2018.hi.en.csv',
 '018-03-01-IND_DSR-_01.03.2018.hi.en.csv',
 '018-03-02-IND_DSR-_02.03.2018.hi.en.csv',
 '018-03-05-IND_DSR-_05.03.2018.hi.en.csv',
 '018-03-07-IND_DSR-_07.03.2018.hi.en.csv',
 '018-03-08-IND_DSR-_08.03.2018.hi.en.csv',
 '018-03-31-IND_DSR-_31.03.2018.hi.en.csv',
 '018-04-01-IND_DSR-_01.04.2018.hi.en.csv',
 '018-04-02-IND_DSR-_02.04.2018.hi.en.csv',
 '018-04-03-IND_DSR-_03.04.2018.hi.en.csv',
 '018-04-05-IND_DSR-_05.04.2018.hi.en.csv',
 'combined2_csv.csv']

In [6]:
import pandas as pd

In [7]:
combined_csv = pd.concat( [ pd.read_csv(file, encoding='latin-1') for file in files ], sort=True )#combining csv files
combined_csv.head()

,Delays cause permanent,Details including the cause of the incident,Event Date and Time,Event site,Permanent date and time,Police Crime / Mrga No.,Sl.,Station,The accused's name and address,The complainant's name and address,section
0,NaN,Fri. That cycle Hero frame and took HQE28177 7...,16:30 between L3-03-l8 14:30,71 Dultganj Indore,3/3/2018 20:10,44/18,1,Station Central station,"Unknown -agyat,","Nazim Ali, father / husband Muktiar Ali reside...","379 Badvi,"
1,The police come to complainant,Motor cycle of an unknown rogue complainant Ho...,16:45 between L3-02-l8 16:30,Native Malwamil intersection Indore front Klali,3/3/2018 20:05,104/18,2,Police Tukoganj,"Agyat-,","Lokendra father / husband, father Dungrsinh ch...","379,"
2,on time,Complainant motor cycles NO. Having the wrong ...,12:45 between 03-03-l8 12:45,Gayatri temple front Indore,3/3/2018 13:40,72/18,3,Police Plasia,Car NO. MP09CL9191 driver -,Imran father / husband Waseem Pathan age 25 ye...,"279, 337"
3,on time,Accused an auto rickshaw driver damaged to hit...,03-03-l8 16:30 of: between,Railway station in front of city bus Indore fr...,3/3/2018 17:40,37/18,4,Thana short Gwaltoli,Auto rickshaw driver number MP 0 9 R 9 088 Dri...,"Manoj Kumar Sharma, father / husband Kedar Pra...","279,"
4,NaN,Shyamal Singh on the second bike with me Jatav...,The 03-03-l8 00:30: Between,SBI scheme number in front of the back 74 Vija...,3/3/2018 12:50,149/18,5,Police Vijayanagar,Car No. MH-02-CL-4496 driver -,"Kapil father / husband, father Mukesh Ruby Age...","337, 279"

In [1]:
type(combined_csv)

NameError: name 'combined_csv' is not defined

In [8]:
combined_csv.to_csv( "combined2_csv.csv", index=False )

In [9]:
ls

 Volume in drive C has no label.
 Volume Serial Number is CAB8-BA77

 Directory of C:\Users\Dell\Desktop\csvfiles

04/09/2019  08:22 PM    <DIR>          .
04/09/2019  08:22 PM    <DIR>          ..
04/09/2019  08:16 PM            26,950 018-02-11-IND_DSR-_11.02.2018.hi.en.csv
04/09/2019  08:16 PM            30,170 018-03-01-IND_DSR-_01.03.2018.hi.en.csv
04/09/2019  08:17 PM            21,875 018-03-02-IND_DSR-_02.03.2018.hi.en.csv
04/09/2019  08:17 PM            24,407 018-03-05-IND_DSR-_05.03.2018.hi.en.csv
04/09/2019  08:18 PM            17,221 018-03-07-IND_DSR-_07.03.2018.hi.en.csv
04/09/2019  08:18 PM            26,238 018-03-08-IND_DSR-_08.03.2018.hi.en.csv
04/09/2019  08:19 PM            27,598 018-03-31-IND_DSR-_31.03.2018.hi.en.csv
04/09/2019  08:19 PM            24,754 018-04-01-IND_DSR-_01.04.2018.hi.en.csv
04/09/2019  08:20 PM            27,882 018-04-02-IND_DSR-_02.04.2018.hi.en.csv
04/09/2019  08:20 PM            30,753 018-04-03-IND_DSR-_03.04.2018.hi.en.csv
04/09/2019  08:20 PM            28,131 018-04-05-IND_DSR-_05.04.2018.hi.en.csv
04/09/2019  07:56 PM            17,188 -03-04-IND_DSR-_04.03.2018_1_.hi.en.csv
04/09/2019  08:14 PM            31,222 -03-06-IND_DSR-_06.03.2018_1_.hi.en.csv
04/09/2019  08:15 PM            24,337 -04-04-IND_DSR-_04.04.2018_1_.hi.en.csv
04/09/2019  08:15 PM            21,854 -04-06-IND_DSR-_06.04.2018.hi.en_1_.csv
04/26/2019  08:08 AM           754,411 combined2_csv.csv
              16 File(s)      1,134,991 bytes
               2 Dir(s)  327,613,239,296 bytes free

In [10]:
f = combined_csv.drop(combined_csv.columns[6], axis=1)

In [11]:
f.head()

,Delays cause permanent,Details including the cause of the incident,Event Date and Time,Event site,Permanent date and time,Police Crime / Mrga No.,Station,The accused's name and address,The complainant's name and address,section
0,NaN,Fri. That cycle Hero frame and took HQE28177 7...,16:30 between L3-03-l8 14:30,71 Dultganj Indore,3/3/2018 20:10,44/18,Station Central station,"Unknown -agyat,","Nazim Ali, father / husband Muktiar Ali reside...","379 Badvi,"
1,The police come to complainant,Motor cycle of an unknown rogue complainant Ho...,16:45 between L3-02-l8 16:30,Native Malwamil intersection Indore front Klali,3/3/2018 20:05,104/18,Police Tukoganj,"Agyat-,","Lokendra father / husband, father Dungrsinh ch...","379,"
2,on time,Complainant motor cycles NO. Having the wrong ...,12:45 between 03-03-l8 12:45,Gayatri temple front Indore,3/3/2018 13:40,72/18,Police Plasia,Car NO. MP09CL9191 driver -,Imran father / husband Waseem Pathan age 25 ye...,"279, 337"
3,on time,Accused an auto rickshaw driver damaged to hit...,03-03-l8 16:30 of: between,Railway station in front of city bus Indore fr...,3/3/2018 17:40,37/18,Thana short Gwaltoli,Auto rickshaw driver number MP 0 9 R 9 088 Dri...,"Manoj Kumar Sharma, father / husband Kedar Pra...","279,"
4,NaN,Shyamal Singh on the second bike with me Jatav...,The 03-03-l8 00:30: Between,SBI scheme number in front of the back 74 Vija...,3/3/2018 12:50,149/18,Police Vijayanagar,Car No. MH-02-CL-4496 driver -,"Kapil father / husband, father Mukesh Ruby Age...","337, 279"

In [12]:
f.tail()

,Delays cause permanent,Details including the cause of the incident,Event Date and Time,Event site,Permanent date and time,Police Crime / Mrga No.,Station,The accused's name and address,The complainant's name and address,section
748,NaN,Complainant that Honda Dream Yogamoksa. Kr.amp...,03-04-l8 9: 0 and 10: 0 beach,Jagdish Eden Gardens complex parking betma,4/4/2018 12:50,178/18,Police betma,"Agyat-,",Sarfaraz Mohammed Age 53 years father / husban...,"379,"
749,NaN,The accused threatened to kill an assault by i...,17:30 between 03-04-l8 17: 0,Complainant's home village Gatabillod Choki,4/4/2018 14:40,179/18,Police betma,Tyyan father Nasser Khan caste Muslims -gatabi...,Ruksarbi caste Muslims aged 25 years father / ...,"323, 452 294 506"
750,On Inquiry application,Dodged the marriage by the accused made forcib...,16/04/10 to 04/25/17,Aspire apartments Bktavr Ramnagar Indore,4/4/2018 13:55,54/18,Mahila Thana,"Sage Ahrwal -ramkumar Ahrwal,",Pidita- age 30 years father Sriramlal Kichi re...,"376 (2) N, 376 (2) N Badvi"
751,On Inquiry application,Dodged the marriage by the accused made forcib...,30/06/11 to 11/13/17,Bholaram master route Bnvrkua Indore,4/4/2018 15:35,55/18,Mahila Thana,"Narendra Kede -gram Kolgav Tehsil Kukshi edge,",Pidita- age 26 years father Balachandas Zawar ...,"376 (2) N, 376 (2) N Badvi"
752,On Inquiry application,By swindle marriage Pidita accused made forcib...,12:11:17 to 08:02:18,303 Face Annex East Ring Road physician city I...,4/4/2018 17:00,56/18,Mahila Thana,Devraj Dangi -303 marked Annex East Ring Road ...,Pidita- age 21 years Jlkre father Jitendra Jlk...,"506, 376 (2) N, 506 Badvi"

In [13]:
f.section.unique()#extracting unique sections from the sections

array(['379 Badvi,', '379,', '279, 337', '279,', '337, 279',
       '324323294506 Badvi,', '174,', '363,', '34 Excise Act,',
       '323, 294/506 Badvi', '427, 294 506 Badvi', '304 Abadvi,',
       '279/337 Badvi,', '25 Ams Act,', '34 Avkari Act,',
       '323, 294 506 Badvi.', '363 Badvi,', '34,',
       '324, 323, 294, 506, 34 Badvi,', '279,337 Badvi,',
       '25 Arms Act, 25 Arms Act', '379, Badvi.', '174 Dkprksnk,',
       '25, B arms act,', '174 Jafo,', '506, 323,294,34', '457, 380',
       '452, 323 294 506 427', 'A 354 7/8 POSCO Act', '174 Jakfuk,',
       '324, 294 506 Takhik ,', '34, (2)', '279, 337 Badvi',
       '25 Arms Act,', '380, Badvi', '323, 294,506,34',
       '323, 294,506,34,', '506, 507', '13', '279,337 Bakdkvik,',
       '323,294,506 Badvi,', '297 294,', '279 337,',
       '4 (a) speculative act,', '327, 324,294,506,34 Bakdkvi,',
       '506/509 Badvi,', '324/326/506/34 Badvi,', '454, 380',
       '327, 341/294/506/34 Badvi and 3 (2) 5 SC / ST Act',
       '323, 294/506/34 Badvi', '279, 337 Badvi.',
       '324, 323,294,506,34 Badvi.', '49A, Excise Act.',
       '323, 294 452 427 506 Badvi', '279, 337 Badvi 184 MV Act',
       '174 Jafo. ,', '8/20 NDPS Act,', '354 Badvi 0 ',
       '4A Max speculative.,', '13 Gambling Act,',
       '279,337 Bakdkvi, 184 motor vehicles Act', '34 Max Excise,',
       '341,294,506,34 Badvi,', '34 (1) Excise Act,', '34 (2) Abakt,',
       '302 Badvi,', '323,294,506,34 Badvi,', '294,323,506,34 Takhik,',
       '381,', '8/27 NDPS Act,', '509,', '323, 294/506', '457,380 Badvi,',
       '49-A, 34 Excise Act, 25 Armsakt', '279 ,, 337', '420,',
       '304 (A) altogether,', '379 Bakdkvik ,',
       '323 294 509 34 Badvi, 3 (1) e, 3 (1) r, 3 (1) s Scheduled Caste and Scheduled Tribe (Prevention of atrocities) Act 1989',
       '4A, speculative Act.', 'Badvi 323, 294 323 506 Badvi',
       '336,323,506,34 Bakdkvik,',
       '279 Bakdkvik, 183,184,185 Motor Vehicles Act',
       '34, 49A binding. Max,', '279, 337 Badvi,',
       '506., 323.294.34 Badvi', '506, 323.294.34 Badvi',
       '363, 363 Badvi', '34 (1) binding act,',
       '354 (a) (d) Badvi, 66 C 66 DIT Act', '4A speculative Act,',
       '279 Badvi, 337 Badvi', '379 IPC,', '323, 294 506', '4A,',
       '188, 283', '294, 323, 506 Badvi', '379 altogether,', '457,',
       '4A state speculative act,', '323, 324/294/506 Badvi',
       '323, 324/294/506/34 Badvi', '341, 327/294/506/34 Badvi',
       '363, Badvi', '12 Passports Act, 1967,', '302, 34',
       '34 Excise Act Snshodint 2000,', '379 Bakdkvik,',
       '25 Arms Act, 27 Arms Act',
       '279,337 Badvi, 184 Motor Vehicles Act',
       '354, Badvi, 294,506 Badvi', '363 Badvi', '324,294 Badvi,',
       '324, 294, 506 Badvi,', '307,506,34 Badvi,', '160 Badvi,',
       '279, Takhi. ., 279,337, Takhik',
       '4A speculative Act, 4A speculative Act', '279 Takhik,',
       '34, 34 Excise Act', '34, 34 Excise Ekt', '379, Badvi', '25,',
       '420, 34', '327,294,323.506,341,34 altogether,', '323 294 506 ,,',
       '392,', '399,402 Badvi, 25 Arms Act', '457,380 altogether,',
       '279., 337 Badvi', '279, 427 Badvi', '457 Badvi, --------',
       '379 Badvi, .....', '279, 337 IPC', '279, 337, Badvi 184 MV Act',
       '25, ...', '323 Bakdkvik, 294,506,34 Bakdkvik',
       'Bakdkvik 323, 294, 506, 34 Bakdkvik', '379 ipc,',
       '354 A, 354 D, Badvi, 506 Badvi', '457, 380 Badvi,',
       '304 (A) Badvi, 279, 337 Badvi', '279 Badvi,', '304 A Badvi,',
       '354 A, 354 D, 294,323,506,34 Badvi, 12 Lagink crimes of Children Protection Act of 2012',
       '34 binding. Act,', '279.337, 279.337', '323, 323.294.506.34',
       '49A,', '49 (a) Excise Act,', '323,294,506,34 altogether,',
       '363 altogether,', '4A, speculative Act', '34, Excise Act',
       '420 ,, 34 Badvi 66 IT Act', '341,294,323,506,34,',
       '8/21 Ankdikpi.as.akt,', '36 (b) Excise Act,',
       '323 ,, 294,506,34 Badvi.', '279, 337 304 A Badvi.',
       '323, 294 506 Badvi', '419 Badvi,',
       '279, 337 Badvi 184 Mokwhi.akt', '457/380 Badvi,',
       '294, 323, 506 Badvi,', '341294323506 Badvi,', '34 A. Excise Act,',
       '13 Juan Act,', '324, 323 294', '25 B. Arms Act,',
       '25, 25 B. Arms Act', '498A, 498A .323.506. Badvi', '34, (1)',
       '279 337 ---', '363 (a) Badvi,',
       '13 Gambling Act, 13 Gambling Act',
       '427,323,294,506,34, Badvi, 3 (1) (d) (d) Ajakajjakadi.',
       '457 380,', '380 Badvi,', '174 Jakfuk, ------',
       '36 (b) Avkari Act,', '4A Gambling Act,', '188 Badvi,',
       '34 (2) Excise Act,', '323, 294, 506 Badvi,', '506, 294 323',
       '379 Takhik ,', '34 (1) Av.akt,', '304-A, 279 337,',
       '352, 323 294 506', '25 Armsakt,', '324, 323/504',
       '452, 294 323 506 altogether', '323,2,94,506,34 ,,', '304-A.,',
       '174 Jakfo,', '323 294, 506', '34 MP Excise Act 1915',
       '324294506, Badvi', '354,323 Badvi', '36 of the Excise Act,',
       '327, 294/506 Badvi', '279, 337 Badvi, 184 Mokwhi. Act',
       '294.506.34 Badvi,', '279 337 Badvi,',
       '323 T The V, 294, 506 T The V',
       '323 Bakdkvi, 294,506,34 affected the V',
       '337 Badvi., 279,337 Badvi.', '420 Badvi,',
       '341 ,, 294,323,506,34 Badvi', '34 (1),', '452, 323 294 506',
       '279,337 Takhik ,', 'Badvi 457.380, 457.380 Badvi',
       '323, 294,506,34 Badvi', '279, Badvi', '324,', '25, Arms Act',
       '160,', '399,402, Bakdkvi, 25 Arms Act', '323, 294, 506, 34 Badvi',
       '452, 327, 427, 323, 294, 506, 336, 34 Badvi', '13 Gambling Act',
       '279.337 Badvi. ,', '323., 294k506kbakdkvik',
       '294 ,, 323,506,34 Badvi', '336.294.506.34 Bakdkvik,',
       '336,294,506. Bakdkvi,', '294 ,, 323, 506, 34',
       '420, 420.467.468.471.34. Badvi',
       '452,354,506., 452..354.506. Badvi 7/8 sexual',
       '294,323,506. Badvi, 294,323,506. Badvi', '399, 402 Badvi',
       '14 District Badr ', '279, 337 338', '451, 353 Badvi,',
       '498-A, 323.34 Badvi 0 ', '279, 337 T The V,',
       '420, 419 altogether', '452/323/294/506/34 Badvi,',
       '323, 324, 294, 506, 34,', '323 294, 506, 34,', '379 Badvi.,',
       '354, 509, 323 294 Badvi.', '336, 427 Badvi.',
       '399, 402, Badvi.avan 25 Arms Act.', '506, 509,294,34 Badvi.',
       '279, 337,323,294,506,34 Badvi', '49A Excise Act,',
       '406, 419,420,467,468,120 B Badvi', '498 A, 323 506 Badvi,',
       '342,323,294,506,147,149 Badvi,', '294,506,34 Badvi,',
       '323. Badvi, 294, 506, 34 Badvi', '185 Motor Vehicle Act',
       '185, Motor Vehicle Act', '420 Badvi 34 Badvi',
       '294, 452, 323, 506, 34', '174 Jakfuk ,', '279.337,',
       '294, 506 Badvi', '283,', '507,', '341, 427/323/294/506',
       '380, 454', '34, Abkariakt', '324,294,506,34 altogether,',
       '279, Badvi.', '324, 294,506,34', '379, 00',
       '8 NDPS Act, 22 NDPS Act', '324 Badvi, 294 Badvi',
       '24 Medical Council Act,', '323,294,506,34,',
       '294, Takhik , 294,323,506,34, Takhik', '304-A,',
       '279, 337 338 304-A', '36, b', '498A, 323, 506, 34 Badvi',
       '294,509, Badvi,', '454,380 Badvi,', '8/22,',
       '323, 294,506,34 Badvi.', '279, 337 Badvi 184 Mv Act',
       '34, 49A binding. Max ..', '363 ..',
       'Section 13 of the Gambling Act,', 'Section 4 Speculation Act,',
       '34 Abakt,', 'Badvi 279, 337, 304 (A) Badvi', '363 Takhik ,',
       '324, 294.34', '323, 294.34', '13 Junaakt', '323, 294 506, 34,',
       '279/337', '380, 457', '363 Badvi 0 ',
       '14 Mkprkrajy Security Act of 1990,', '279,337 Bakdkvi,',
       '304 A, 34 Bakdkvi,', '379 Bakdkvi,', '506, 323 294,',
       '506 Badvi, 323,294 Badvi', '279 Badvi, 184 Mokwhi.akt',
       '323,294,506,384,34 Badvi 0 ', '379, Badvi 0 ', '379 Badvi 0  ',
       '325, 504 323, 34', '363 Bakdkvik,', '323, Badvi, 294, 506 Badvi',
       '294,323,506,34 Badvi,', '34 Ab.akt,', '457,380 Takhik ,',
       '294 323, 506, Badvi 0 ', '323,', '294, 323', '354',
       '323, 294,506,427,34,', '279, 427', '454 380,',
       '420, 467 468, 471 120 B Badvi', '498-A, 506.34 Badvi 0 ',
       '354 Badvi 0, 7/8 Pasco Act',
       '354 354-D, 506 Badvi 0 AND 7/18 Pasco Act',
       'In 14 g. Max state security. 188 Badvi,', '36 b Excise Act,',
       '34 MP. Excise Act 1915', '363, 366 376 506 Badvi.',
       '354 D, 509/506', '323,506,34 Bakdkvik,',
       '323, 294, 506, 34 Badvi,', '34 (A) Excise Act,',
       '323,324,294,506,34 Badvi,', '380,', 'Badvi 279, 337, 304 A Badvi',
       '25 A. Arms Act,', '34.36 A Ab.akt,', '279, 337 Takhik ,',
       '188, Badvi 0 15 Max Pryaksnrkshn., 4/9 max Mkprkpeyjl shielding.',
       '435,', ' 8/20 NDPS Act', '323, 294.506.34', '337, 279 altogether',
       '457,380 Bakdkvik ,', '4A Dhoot Act,', '379 Badvi, -----',
       '4A) public Dhrut Act, 00', '406, 419/420', '8/22 NDPS Act',
       '323294506, Badvi 0  ', '304 A,', 'Section 379 Badvi,',
       'Section 25 of the Arms Act,', '406 Badvi,', '294, 323,506,34',
       '279 ,, 294,323,506,34', '323, 452 294 506',
       '376 (2) N, 376 (2) N Badvi', '506, 376 (2) N, 506 Badvi'],
      dtype=object)

In [14]:
print(f.loc[f['section'] == '379,'])

                                Delays cause permanent  \
1                       The police come to complainant
5                                                  NaN
9                                                  NaN
27                                                 NaN
43                          On the station's plaintive
3    To not meet after searching today police repor...
5                              Come on station Friadia
17                      The police come to complainant
48                                                 NaN
8                                                  NaN
41                                                 NaN
2                                                  NaN
6                                                  NaN
7                                                  NaN
9                At the time police arrive complainant
10                Complainant timely Kea police arrive
22                      The police come to complainant
0                                                   L'
1                                                  NaN
14                                                 NaN
26                         Thauna when the complainant
3                                        Looking after
4                                          After Talas
7                                                  NaN
13                                                 NaN
28                                                 NaN
0                                                  NaN
10                                                 NaN
12                                                 NaN
27                                               Talas
..                                                 ...
255                                                NaN
267                        Thauna when the complainant
306                                      Looking after
307                                        After Talas
310                                                NaN
316                                                NaN
331                                                NaN
347                                                NaN
357                                                NaN
359                                                NaN
374                                              Talas
436                                                NaN
442                                             search
443                                                NaN
487   He came to the police station of the complainant
536  Talas stayed at not meeting did report dated t...
540                             Come on station Friadi
547                                                NaN
561  After looking at the police station of the com...
562                         On the station's plaintive
586                                                NaN
591                            Come on station Friadia
595                                                NaN
640  Today I am here to report on the meeting not b...
651                                                NaN
658                                                NaN
661                                                NaN
698                                 Been around Talas.
716                        On Thanaane the complainant
748                                                NaN

           Details including the cause of the incident  \
1    Motor cycle of an unknown rogue complainant Ho...
5    At around noon 04/00 AM 21/02/2018 I have my b...
9    At close of the morning 10/00 AM 03/03/2018 I ...
27   An unknown rascal scooter Honda housed space c...
43   An unknown rogue bike the complainant Bajaj Pl...
3    Mo to an unknown rogue complainant. Sa. Bajaj ...
5    Friadia dated 02/04/18 was the evening to Indo...
17   There was an unknown individual complainant's ...
48   Complainant placed in bags and took 17000 Rs s...
8    Accused Fri 0 bike Hero Honda Splandr MP09.MV....
41   Complainant that Hiro pension Pro car. MP 0 9 ...
2    Complainant and took his Activa Scooter No. MP...
6    Accused Fri 0 Bajaj Vikrant bike MP45ML0525 Ch...
7    Accused Fri 0 bike Hero Honda Spalendr Pro. No...
9    Accused Fri 0 bike hero HFC deluxe car. MP09VD...
10   Accused Fri 0 bike hero HFC deluxe car. MP09BV...
22   An unknown person steals the location housed t...
0    An unknown rogue my Honda Aktiwa NO. MP09SR968...
1    An unknown rogue my Moksak Honda Shine MP09NH8...
14   Complainant motorcycle Bajaj Pulsar 150 cc new...
26   Put an unknown rogue lock the trunk of the car...
3    Date 25/02/2018 came to see Tue City merchandi...
4    Date 23/02/2018 afternoon his motorcycle hero ...
7    At around noon 04/50 AM 25/02/2018 I your moto...
13   Hiro the complainant by unknown accused Deluxe...
28   MPEB has take-current transformer (Sikti) stol...
0    The moss take stole the location housed the mo...
10   The accused did not bike Hero Deluxe Fri 0. MP...
12   Accused Fri 0 bike Pulsar 180 cc No. UP14.AP.4...
27   Mo by unknown accused. Sl. MP09QN9003 Pulsar a...
..                                                 ...
255  Complainant motorcycle Bajaj Pulsar 150 cc new...
267  Put an unknown rogue lock the trunk of the car...
306  Date 25/02/2018 came to see Tue City merchandi...
307  Date 23/02/2018 afternoon his motorcycle hero ...
310  At around noon 04/50 AM 25/02/2018 I your moto...
316  Hiro the complainant by unknown accused Deluxe...
331  MPEB has take-current transformer (Sikti) stol...
347  The moss take stole the location housed the mo...
357  The accused did not bike Hero Deluxe Fri 0. MP...
359  Accused Fri 0 bike Pulsar 180 cc No. UP14.AP.4...
374  Mo by unknown accused. Sl. MP09QN9003 Pulsar a...
436  Moksak unknown accused complainant Hero Honda ...
442  At around noon, 4.30 pm 03.03.2018 I have my b...
443  The accused took the stole from the hotel hous...
487  Complainant his motor Saikilplsr 150cc Blade r...
536  Honda Aktiwa car of the complainant by unknown...
540  Fryadi the No. Your Magic car. MP 0 9 / T / 68...
547  Scooter Honda AMCYSC the complainant car. MP09...
561  Took unknown rogue pension Pro MP09QY4808 Chec...
562  Unknown person I the purse in which a redmi of...
586  Mo to an unknown rogue complainant. Sa. Bajaj ...
591  Friadiay has brought its Activa Super Kr.ampi ...
595  Date 03/26/18 Hero Spelendr bike was number MP...
640  Yamaha R15 V2 No. unknown accused rogue compla...
651  Date came at my store Around 8.30 pm 03.29.201...
658  An unknown Arhopi took an unknown crooks stole...
661  Complainant bike Hero Honda Splendr car. MP10 ...
698  Unknown accused hero of the complainant Honda ...
716  There was an unknown Vykti complainant's Honda...
748  Complainant that Honda Dream Yogamoksa. Kr.amp...

                Event Date and Time  \
1      16:45 between L3-02-l8 16:30
5      2l-02-l8 16: 16:30 between 0
9      13:30 between 03-03-l8 13: 0
27             27-02-l8 7: 0: Beach
43         L4-l2-l7 8: 9 0: 0 beach
3    28-03-l8 20: 0 and 21: 0 beach
5      19:30 between 02-04-l8 19: 0
17      3l-03-l8 20: 0, 20: 0 beach
48    The 25-03-l8 17:10 0: 0 beach
8      22 03-04-l8 21:30: between 0
41   3l-03-l8 19: 0 and 21: 0 beach
2      21:30 between 08-02-l8 19:30
6                                 0
7      13:30 between 08-02-l8 13: 0
9     08-02-l8 10:30 to 11: 0 beach
10     13:30 between 08-02-l8 13:15
22   08-02-l8 11: 0 and 12: 0 beach
0      21:30 between 25-02-l8 21: 0
1      23:15 between 24-02-l8 21:15
14    0l-03-l8 13:30 to 14: 0 beach
26     19:45 between 28-02-l8 19: 0
3      19:45 between 25-02-l8 16:30
4      22 23-02-l8 13:25: between 0
7      25-02-l8 19:30 between 16:50
13     26-02-18 20:30 21: between 0
28      27-02-l8 19: 0, 19: 0 beach
0      13:30 between 28-02-l8 12:30
10    08-02-l8 13:30 to 14: 0 beach
12     20:15 between 02-03-l8 19:30
27     04-03-l8 18: 22: 0 between 0
..                              ...
255   0l-03-l8 13:30 to 14: 0 beach
267    19:45 between 28-02-l8 19: 0
306    19:45 between 25-02-l8 16:30
307    22 23-02-l8 13:25: between 0
310    25-02-l8 19:30 between 16:50
316    26-02-18 20:30 21: between 0
331     27-02-l8 19: 0, 19: 0 beach
347    13:30 between 28-02-l8 12:30
357   08-02-l8 13:30 to 14: 0 beach
359    20:15 between 02-03-l8 19:30
374    04-03-l8 18: 22: 0 between 0
436     28-02-l8 19: 0, 19: 0 beach
442    17:30 between 03-03-l8 16:30
443    14:30 between 03-03-l8 13: 0
487  30-03-l8 14: 0 and 16: 0 beach
536    21:30 between 26-03-l8 20:45
540        3l-03-l8 4: 0 4: 0 beach
547    19:30 between 29-03-l8 19: 0
561    19-03-18 20:30 21: between 0
562    18: 0 between 3l-03-l8 17:45
586   27-03-l8 11:15 to 19: 0 beach
591    16:30 between 3l-03-l8 13:30
595   26-03-l8 13:30 to 17: 0 beach
640  29-03-l8 10: 0 and 16: 0 beach
651    29-03-l8 21:15 between 20:30
658    22:30 between 0l-04-l8 16:30
661  3l-03-l8 12: 0 and 13: 0 beach
698    17:15 between 3l-03-l8 16:30
716       02-04-l8 21:30 9: 0 beach
748   03-04-l8 9: 0 and 10: 0 beach

                                            Event site  \
1      Native Malwamil intersection Indore front Klali
5                     Business Park Indore near bridge
9    18/4-B. Vijayanagar Jain Indore in front of te...
27   Neha Khatiwala tank Indore in front of the Palace
43          English wine shop Navdapnth Ringrod Indore
3    Ford show have t material in front of the room...
5           Indore front of city extension Kalndi park
17              Devasree Takij near Iron Market Indore
48                 Kohinoor Edge Road betma near Dhaba
8             C21 Vijayanagar Indore in front of goods
41             Hanuman temple complex Gatabillod Choki
2              C HL Aspaktal Behind the parking Indore
6                              8/32 Vijay Nagar Indore
7                  BSNL's parking Malviya Nagar Indore
9    E B 216 not scheme. 94 Near Bombay Hospital, I...
10   PLOT NO .462,463 A sector Mahalakshmi Nagar In...
22        46 Type 2 BSNL quarters Khatiwalatank Indore
0           Malwamil community recently outside Indore
1    Punjab Arodvshiy sidewalk in front of the hosp...
14             Mkn 0.81 ° B front splendor city Indore
26                    Sadhu Vaswani Garden near Indore
3                 Parking Indore behind Sthl?mngl City
4               Malhar parking Indore behind the goods
7        Tue City that Parking Indore behind the goods
13                     Out of 1172/28 Nandanagr Indore
28              Navdapnth Power House Edge Road Indore
0    Subhash Chowk Power House Bohra mosque near In...
10                Cemeteries Bmori Indore outside pier
12       Malhar Mega goods outside parking Road Indore
27                          146 Lotus Park City Indore
..                                                 ...
255           Mkn 0.81 Â° B front splendor city Indore
267                   Sadhu Vaswani Garden near Indore
306               Parking Indore behind Sthl?mngl City
307             Malhar parking Indore behind the goods
310      Tue City that Parking Indore behind the goods
316                    Out of 1172/28 Nandanagr Indore
331             Navdapnth Power House Edge Road Indore
347  Subhash Chowk Power House Bohra mosque near In...
357               Cemeteries Bmori Indore outside pier
359      Malhar Mega goods outside parking Road Indore
374                         146 Lotus Park City Indore
436  Punjab Arod septal Indore in front of the hospice
442           C21 Vijayanagar Indore in front of goods
443          Bhopal Bahra V Road Indore Motor Showroom
487          13 9 Krishna Complex Frdnis Colony Indore
536    HDFC Bank's Alley South Tukoganj MG Road Indore
540  Patnipura Common Road Bhairon Baba Indore near...
547  Jlaria Road Knadia Indore near the complainant...
561  Temporary parking Annapurna Road Indore Dusseh...
562     Chankyapuri intersection Hanuman temple Indore
586            Starling Arket tower parking RCR Indore
591  Christian Minen school before press Complex In...
595        Parking Vijay Nagar Indore Madanta hospital
640         14/7 New Plasia near Laxmi Memorial Indore
651                 Gopal Traders Scheme No. 74 Indore
658  Chris apartments 14-15 Paras Dham Colony near ...
661  159 communication Nagar extension Knadia Road ...
698  Forest goods Gem House in front of 56 women In...
716  28 Sarvodaya Nagar in front of the district In...
748         Jagdish Eden Gardens complex parking betma

    Permanent date and time Police Crime / Mrga No.              Station  \
1            3/3/2018 20:05                  104/18      Police Tukoganj
5            3/3/2018 19:45                  150/18   Police Vijayanagar
9            3/5/2018 14:40                  154/18   Police Vijayanagar
27           3/5/2018 19:10                  120/18   Police Juni Indore
43           3/5/2018 19:45                  177/18  Police Chandannagar
3            4/3/2018 16:15                  150/18      Police Tukoganj
5            4/3/2018 11:30                  234/18           Police MIG
17            4/3/2018 0:55                  159/18   Police Juni Indore
48           4/3/2018 16:10                  177/18         Police betma
8            4/5/2018 14:00                  237/18   Police Vijayanagar
41           4/5/2018 12:10                  181/18         Police betma
2           2/10/2018 12:00                  117/18           Police MIG
6           2/10/2018 14:15                   98/18   Police Vijayanagar
7           2/10/2018 13:00                   97/18   Police Vijayanagar
9           2/10/2018 14:15                  129/18        Police Lsudia
10          2/10/2018 14:20                  130/18        Police Lsudia
22          2/10/2018 12:45                   89/18   Police Juni Indore
0           2/28/2018 13:10                  100/18      Police Tukoganj
1           2/28/2018 14:45                  101/18      Police Tukoganj
14          2/28/2018 17:40                   80/18        Police Knadia
26          2/28/2018 22:00                  114/18   Police Juni Indore
3            3/1/2018 12:00                  143/18   Police Vijayanagar
4            3/1/2018 14:30                  144/18   Police Vijayanagar
7            3/1/2018 16:30                  147/18   Police Vijayanagar
13           3/1/2018 22:30                  112/18  Police Pardeshipura
28           3/1/2018 16:40                  161/18  Police Chandannagar
0            3/4/2018 16:40                  101/18      Station MG Road
10           3/4/2018 12:40                  151/18   Police Vijayanagar
12           3/4/2018 18:35                  153/18   Police Vijayanagar
27           3/4/2018 19:50                  237/18     Police Baanganga
..                      ...                     ...                  ...
255         2/28/2018 17:40                   80/18        Police Knadia
267         2/28/2018 22:00                  114/18   Police Juni Indore
306          3/1/2018 12:00                  143/18   Police Vijayanagar
307          3/1/2018 14:30                  144/18   Police Vijayanagar
310          3/1/2018 16:30                  147/18   Police Vijayanagar
316          3/1/2018 22:30                  112/18  Police Pardeshipura
331          3/1/2018 16:40                  161/18  Police Chandannagar
347          3/4/2018 16:40                  101/18      Station MG Road
357          3/4/2018 12:40                  151/18   Police Vijayanagar
359          3/4/2018 18:35                  153/18   Police Vijayanagar
374          3/4/2018 19:50                  237/18     Police Baanganga
436          3/7/2018 20:40                  112/18      Police Tukoganj
442          3/7/2018 18:05                  158/18   Police Vijayanagar
443          3/7/2018 14:00                  214/18        Police Lsudia
487         3/30/2018 16:00                  221/18           Police MIG
536         3/31/2018 12:10                  142/18      Police Tukoganj
540         3/31/2018 10:55                  224/18           Police MIG
547         3/31/2018 17:20                  124/18        Police Knadia
561         3/31/2018 20:05                  118/18     Police Annapurna
562         3/31/2018 21:00                  120/18     Police Annapurna
586          4/1/2018 15:00                  144/18      Police Tukoganj
591          4/1/2018 14:00                  227/18           Police MIG
595          4/1/2018 12:00                  226/18   Police Vijayanagar
640          4/2/2018 13:40                  145/18      Police Tukoganj
651          4/2/2018 20:00                  229/18   Police Vijayanagar
658          4/2/2018 11:45                  109/18  Station Tilak Nagar
661          4/2/2018 18:05                  128/18        Police Knadia
698          4/4/2018 11:55                  151/18      Police Tukoganj
716           4/4/2018 0:00                  162/18   Police Juni Indore
748          4/4/2018 12:50                  178/18         Police betma

    The accused's name and address  \
1                          Agyat-,
5                         Agyatk-,
9                         Agyatk-,
27                         Agyat-,
43                         Agyat-,
3                        Unknown -
5                     Unknown con,
17                       Unknown -
48                         Agyat-,
8                         Agyatk-,
41                         Agyat-,
2                     Unknown con,
6                        Unknown -
7                        Unknown -
9                unknown person -,
10               unknown person -,
22                       Unknown -
0                        Unknown -
1                        Unknown -
14                         Agyat-,
26                       Unknown -
3                          Agyat-,
4                          Agyat-,
7                         Agyatk-,
13                         Agyat-,
28                         Agyat-,
0                          Agyat-,
10                        Agyatk-,
12                        Agyatk-,
27                         Agyat-,
..                             ...
255                        Agyat-,
267                      Unknown -
306                        Agyat-,
307                        Agyat-,
310                       Agyatk-,
316                        Agyat-,
331                        Agyat-,
347                        Agyat-,
357                       Agyatk-,
359                       Agyatk-,
374                        Agyat-,
436                      Unknown -
442                       Agyatk-,
443              unknown person -,
487              Unknown thieves -
536                      Unknown -
540              Unknown thieves -
547                      Unknown -
561                        Agyat-,
562                      Unknown -
586                      Unknown -
591              Unknown thieves -
595                       Agyatk-,
640                        Agyat-,
651                       Agyatk-,
658                      Unknown -
661                      Unknown -
698                        Agyat-,
716                      Unknown -
748                        Agyat-,

                    The complainant's name and address section
1    Lokendra father / husband, father Dungrsinh ch...    379,
5    Dharmendra father / husband Rbnvr red Billore ...    379,
9    Kallu father / husband's father Mr. raghuveer ...    379,
27   Ravi Pahuja father / husband Radhakisn Pahuja ...    379,
43   Laxminarayan age 39 years Moknank 9691763908 f...    379,
3    Abhishek Dwivedi age 23 mo. 8889537989 father ...    379,
5    Priyanka's father / husband Shyamal Dhurve res...    379,
17   Mayank Gwate father / husband Arun Gwate resid...    379,
48   Smndersih chivalrous age 70 father / husband K...    379,
8    Abhash Shah father / husband's father Naresh S...    379,
41   Ctrsih Suner caste Rajput father / husband Bap...    379,

In [15]:
unique_shit = f.section #unique sections

In [16]:
unique_shit

0                         379 Badvi,
1                               379,
2                           279, 337
3                               279,
4                           337, 279
5                               379,
6                324323294506 Badvi,
7                               174,
8                               363,
9                     34 Excise Act,
10                323, 294/506 Badvi
11                427, 294 506 Badvi
12                       304 Abadvi,
13                    279/337 Badvi,
14                       25 Ams Act,
15                        379 Badvi,
16                    34 Avkari Act,
17               323, 294 506 Badvi.
18                        363 Badvi,
19                               34,
20                               34,
21     324, 323, 294, 506, 34 Badvi,
22                    279,337 Badvi,
23          25 Arms Act, 25 Arms Act
24                       379, Badvi.
25                     174 Dkprksnk,
26                   25, B arms act,
27                         174 Jafo,
28                    279,337 Badvi,
29                   506, 323,294,34
                   ...
723         4A) public Dhrut Act, 00
724                     406, 419/420
725                         279, 337
726                         380, 457
727                    8/22 NDPS Act
728                         380, 457
729                       379, Badvi
730             323294506, Badvi 0
731                       379 Badvi,
732            294,323,506,34 Badvi,
733                           304 A,
734                         279, 337
735                  25 B. Arms Act,
736               Section 379 Badvi,
737      Section 25 of the Arms Act,
738                       406 Badvi,
739                         279, 337
740                              34,
741                  294, 323,506,34
742            279 ,, 294,323,506,34
743                       34 Ab.akt,
744                 34 binding. Act,
745                 34 binding. Act,
746                 34 binding. Act,
747                       34 Ab.akt,
748                             379,
749                 323, 452 294 506
750       376 (2) N, 376 (2) N Badvi
751       376 (2) N, 376 (2) N Badvi
752        506, 376 (2) N, 506 Badvi
Name: section, Length: 1506, dtype: object

In [17]:
unique_shit.str

In [18]:
unique_shit = pd.Series(unique_shit)

In [19]:
type(unique_shit)

pandas.core.series.Series

In [20]:
unique_shit

0                         379 Badvi,
1                               379,
2                           279, 337
3                               279,
4                           337, 279
5                               379,
6                324323294506 Badvi,
7                               174,
8                               363,
9                     34 Excise Act,
10                323, 294/506 Badvi
11                427, 294 506 Badvi
12                       304 Abadvi,
13                    279/337 Badvi,
14                       25 Ams Act,
15                        379 Badvi,
16                    34 Avkari Act,
17               323, 294 506 Badvi.
18                        363 Badvi,
19                               34,
20                               34,
21     324, 323, 294, 506, 34 Badvi,
22                    279,337 Badvi,
23          25 Arms Act, 25 Arms Act
24                       379, Badvi.
25                     174 Dkprksnk,
26                   25, B arms act,
27                         174 Jafo,
28                    279,337 Badvi,
29                   506, 323,294,34
                   ...
723         4A) public Dhrut Act, 00
724                     406, 419/420
725                         279, 337
726                         380, 457
727                    8/22 NDPS Act
728                         380, 457
729                       379, Badvi
730             323294506, Badvi 0
731                       379 Badvi,
732            294,323,506,34 Badvi,
733                           304 A,
734                         279, 337
735                  25 B. Arms Act,
736               Section 379 Badvi,
737      Section 25 of the Arms Act,
738                       406 Badvi,
739                         279, 337
740                              34,
741                  294, 323,506,34
742            279 ,, 294,323,506,34
743                       34 Ab.akt,
744                 34 binding. Act,
745                 34 binding. Act,
746                 34 binding. Act,
747                       34 Ab.akt,
748                             379,
749                 323, 452 294 506
750       376 (2) N, 376 (2) N Badvi
751       376 (2) N, 376 (2) N Badvi
752        506, 376 (2) N, 506 Badvi
Name: section, Length: 1506, dtype: object

In [21]:
unique_shit = unique_shit.str.replace('[\- /,.a-zA-Z]+|\(\d\)|\(|\)', ' ')#cleaning the data by removing alphabets
unique_shit

0                     379
1                     379
2                  279 337
3                     279
4                  337 279
5                     379
6            324323294506
7                     174
8                     363
9                      34
10            323 294 506
11            427 294 506
12                    304
13                279 337
14                     25
15                    379
16                     34
17            323 294 506
18                    363
19                     34
20                     34
21     324 323 294 506 34
22                279 337
23                  25 25
24                    379
25                    174
26                     25
27                    174
28                279 337
29          506 323 294 34
              ...
723                 4   00
724            406 419 420
725                279 337
726                380 457
727                  8 22
728                380 457
729                   379
730           323294506 0
731                   379
732        294 323 506 34
733                   304
734                279 337
735                    25
736                   379
737                    25
738                   406
739                279 337
740                    34
741         294 323 506 34
742     279 294 323 506 34
743                    34
744                    34
745                    34
746                    34
747                    34
748                   379
749        323 452 294 506
750           376   376
751           376   376
752         506 376   506
Name: section, Length: 1506, dtype: object

In [22]:
dummy_shit = unique_shit.str.get_dummies(sep=' ')
print(dummy_shit.columns)
dummy_shit = dummy_shit[['379', '13', '279', '323', '363', '302']]

Index(['0', '00', '12', '120', '13', '14', '147', '149', '15', '160', '174',
       '18', '183', '184', '185', '188', '1915', '1967', '1989', '1990', '2',
       '20', '2000', '2012', '21', '22', '24', '25', '27', '279', '283', '294',
       '297', '3', '302', '304', '307', '323', '323294506', '324', '324294506',
       '324323294506', '325', '326', '327', '336', '337', '338', '34', '341',
       '341294323506', '342', '352', '353', '354', '36', '363', '366', '376',
       '379', '380', '381', '384', '392', '399', '4', '402', '406', '419',
       '420', '427', '435', '451', '452', '454', '457', '467', '468', '471',
       '49', '498', '5', '504', '506', '507', '509', '66', '7', '8', '9',
       '94'],
      dtype='object')

In [23]:
print(dummy_shit)

     379  13  279  323  363  302
0      1   0    0    0    0    0
1      1   0    0    0    0    0
2      0   0    1    0    0    0
3      0   0    1    0    0    0
4      0   0    1    0    0    0
5      1   0    0    0    0    0
6      0   0    0    0    0    0
7      0   0    0    0    0    0
8      0   0    0    0    1    0
9      0   0    0    0    0    0
10     0   0    0    1    0    0
11     0   0    0    0    0    0
12     0   0    0    0    0    0
13     0   0    1    0    0    0
14     0   0    0    0    0    0
15     1   0    0    0    0    0
16     0   0    0    0    0    0
17     0   0    0    1    0    0
18     0   0    0    0    1    0
19     0   0    0    0    0    0
20     0   0    0    0    0    0
21     0   0    0    1    0    0
22     0   0    1    0    0    0
23     0   0    0    0    0    0
24     1   0    0    0    0    0
25     0   0    0    0    0    0
26     0   0    0    0    0    0
27     0   0    0    0    0    0
28     0   0    1    0    0    0
29     0   0    0    1    0    0
..   ...  ..  ...  ...  ...  ...
723    0   0    0    0    0    0
724    0   0    0    0    0    0
725    0   0    1    0    0    0
726    0   0    0    0    0    0
727    0   0    0    0    0    0
728    0   0    0    0    0    0
729    1   0    0    0    0    0
730    0   0    0    0    0    0
731    1   0    0    0    0    0
732    0   0    0    1    0    0
733    0   0    0    0    0    0
734    0   0    1    0    0    0
735    0   0    0    0    0    0
736    1   0    0    0    0    0
737    0   0    0    0    0    0
738    0   0    0    0    0    0
739    0   0    1    0    0    0
740    0   0    0    0    0    0
741    0   0    0    1    0    0
742    0   0    1    1    0    0
743    0   0    0    0    0    0
744    0   0    0    0    0    0
745    0   0    0    0    0    0
746    0   0    0    0    0    0
747    0   0    0    0    0    0
748    1   0    0    0    0    0
749    0   0    0    1    0    0
750    0   0    0    0    0    0
751    0   0    0    0    0    0
752    0   0    0    0    0    0

[1506 rows x 6 columns]

In [32]:
dummy_shit.to_csv('C://Users//Dell//Desktop/crime-prediction-master//master//dummied.csv', encoding='latin-1')

In [33]:
dumy_shit = pd.read_csv('C://Users//Dell//Desktop/crime-prediction-master//master//data.csv')

In [30]:
dummy_shit['latlon'] = (dumy_shit['latitude'].map('{0:.6f}'.format) + ',' + dumy_shit['longitude'].map('{0:.6f}'.format))
#print(data['latlon'])

In [31]:
print(dummy_shit['latlon'])

0      22.737260,75.875987
1      22.720992,75.876083
2      22.736676,75.883168
3      22.746527,75.887139
4      22.769531,75.888772
5      22.735218,75.913366
6      22.736766,75.908579
7      22.736766,75.908579
8      22.722247,75.915294
9      22.722247,75.915294
10     22.741662,75.869137
11     22.741662,75.869137
12     22.746877,75.883168
13     22.744534,75.931421
14     22.765772,75.870461
15     22.767806,75.875984
16     22.715210,75.870047
17     22.698342,75.910757
18     22.694114,75.904223
19     22.711535,75.860105
20     22.715121,75.856601
21     22.719961,75.843657
22     22.719961,75.843657
23     22.727249,75.853214
24     22.726920,75.851580
25     22.726920,75.851580
26     22.726920,75.851580
27     22.723873,75.828416
28     22.723873,75.828416
29     22.723873,75.828416
              ...
723    22.703141,75.861505
724    22.701789,75.866702
725    22.699680,75.864652
726    22.711535,75.860105
727    22.711535,75.860105
728    22.757062,75.882186
729    22.757062,75.882186
730    22.706070,75.860504
731    22.714156,75.856339
732    22.726750,75.881079
733    22.721868,75.874134
734    22.721040,75.903652
735    22.729645,75.897313
736    22.813268,75.848615
737    22.745585,75.860658
738    22.744118,75.894023
739    22.792347,75.907511
740    22.792347,75.907511
741    22.741773,75.923824
742    22.741773,75.923824
743    22.728835,75.879600
744    22.771026,75.851612
745    22.707853,75.860957
746    22.707853,75.860957
747    22.710027,75.862469
748    22.683873,75.879972
749    22.673236,75.874455
750    22.714573,75.846375
751    22.707243,75.842508
752    22.713983,75.841481
Name: latlon, Length: 1506, dtype: object

In [151]:
print(dumy_shit[['latitude','longitude']])

       latitude  longitude
0     22.737260  75.875987
1     22.720992  75.876083
2     22.736676  75.883168
3     22.746527  75.887139
4     22.769531  75.888772
5     22.735218  75.913366
6     22.736766  75.908579
7     22.736766  75.908579
8     22.722247  75.915294
9     22.722247  75.915294
10    22.741662  75.869137
11    22.741662  75.869137
12    22.746877  75.883168
13    22.744534  75.931421
14    22.765772  75.870461
15    22.767806  75.875984
16    22.715210  75.870047
17    22.698342  75.910757
18    22.694114  75.904223
19    22.711535  75.860105
20    22.715121  75.856601
21    22.719961  75.843657
22    22.719961  75.843657
23    22.727249  75.853214
24    22.726920  75.851580
25    22.726920  75.851580
26    22.726920  75.851580
27    22.723873  75.828416
28    22.723873  75.828416
29    22.723873  75.828416
...         ...        ...
2060  22.706070  75.860504
2061  22.714156  75.856339
2062  22.726750  75.881079
2063  22.721868  75.874134
2064  22.721040  75.903652
2065  22.729645  75.897313
2066  22.813268  75.848615
2067  22.745585  75.860658
2068  22.744118  75.894023
2069  22.792347  75.907511
2070  22.792347  75.907511
2071  22.741773  75.923824
2072  22.741773  75.923824
2073  22.728835  75.879600
2074  22.771026  75.851612
2075  22.707853  75.860957
2076  22.707853  75.860957
2077  22.710027  75.862469
2078  22.683873  75.879972
2079  22.673236  75.874455
2080  22.714573  75.846375
2081  22.707243  75.842508
2082  22.713983  75.841481
2083  22.709760  75.830908
2084  22.708832  75.828798
2085  22.712970  75.823580
2086  22.693481  75.821483
2087  22.531931  75.769126
2088  22.719569  75.857726
2089  22.686437  76.032055

[2090 rows x 2 columns]

In [136]:
print((f['Permanent date and time']))

0     3/3/2018 20:10
1     3/3/2018 20:05
2     3/3/2018 13:40
3     3/3/2018 17:40
4     3/3/2018 12:50
5     3/3/2018 19:45
6      3/3/2018 4:10
7     3/3/2018 22:55
8     3/3/2018 23:40
9     3/3/2018 11:00
10    3/3/2018 20:05
11    3/3/2018 21:20
12    3/3/2018 11:20
13    3/3/2018 13:00
14    3/3/2018 14:00
15    3/3/2018 15:30
16     3/3/2018 0:20
17     3/3/2018 0:15
18    3/3/2018 14:10
19    3/3/2018 12:05
20    3/3/2018 19:35
21    3/3/2018 22:50
22    3/3/2018 23:10
23    3/3/2018 12:30
24    3/3/2018 14:05
25     3/3/2018 3:15
26    3/3/2018 16:40
27    3/3/2018 16:10
28    3/3/2018 19:20
29    3/3/2018 13:35
           ...
26    4/4/2018 14:00
27    4/4/2018 20:20
28     4/4/2018 4:10
29    4/4/2018 13:35
30    4/4/2018 18:15
31    4/4/2018 21:30
32    4/4/2018 16:15
33    4/4/2018 19:45
34    4/4/2018 16:25
35     4/4/2018 0:55
36    4/4/2018 13:50
37    4/4/2018 18:30
38    4/4/2018 21:55
39    4/4/2018 10:50
40    4/4/2018 18:25
41    4/4/2018 19:30
42    4/4/2018 15:15
43    4/4/2018 20:35
44    4/4/2018 20:50
45    4/4/2018 21:25
46    4/4/2018 17:40
47    4/4/2018 17:55
48    4/4/2018 18:10
49    4/4/2018 18:20
50    4/4/2018 18:40
51    4/4/2018 12:50
52    4/4/2018 14:40
53    4/4/2018 13:55
54    4/4/2018 15:35
55    4/4/2018 17:00
Name: Permanent date and time, Length: 753, dtype: object

In [149]:
print(dumy_shit)

             timestamp  act379  act13  act279  act323  act363  act302  \
0     28-02-2018 21:00       1      0       0       0       0       0
1     28-02-2018 21:15       1      0       0       0       0       0
2     28-02-2018 10:15       0      0       1       0       0       0
3     28-02-2018 10:15       0      0       1       0       0       0
4     28-02-2018 10:30       0      0       1       0       0       0
5     28-02-2018 14:15       0      0       0       1       0       0
6     28-02-2018 08:00       0      0       0       0       1       0
7     28-02-2018 03:30       0      0       0       1       0       0
8     28-02-2018 01:30       1      0       0       0       0       0
9     28-02-2018 19:00       0      0       0       1       0       0
10    28-02-2018 14:10       0      0       0       1       0       0
11    28-02-2018 14:25       0      0       0       1       0       0
12    28-02-2018 22:00       0      1       0       0       0       0
13    28-02-2018 22:00       0      0       0       1       0       0
14    28-02-2018 22:10       0      0       0       1       0       0
15    28-02-2018 12:00       1      0       0       0       0       0
16    28-02-2018 13:30       0      0       0       0       1       0
17    28-02-2018 03:00       0      0       0       1       0       0
18    28-02-2018 23:50       0      0       0       1       0       0
19    28-02-2018 19:00       1      0       0       0       0       0
20    28-02-2018 11:55       0      0       1       0       0       0
21    28-02-2018 11:00       0      0       0       1       0       0
22    28-02-2018 18:00       0      0       1       0       0       0
23    28-02-2018 01:00       0      0       0       1       0       0
24    28-02-2018 00:00       1      0       0       0       0       0
25    28-02-2018 22:10       0      0       1       0       0       0
26    28-02-2018 22:30       0      1       0       0       0       0
27    28-02-2018 08:40       0      0       1       0       0       0
28    28-02-2018 15:40       0      0       0       1       0       0
29    28-02-2018 15:50       0      0       0       1       0       0
...                ...     ...    ...     ...     ...     ...     ...
2060    6/3/2018 11:30       0      0       1       0       0       0
2061    6/3/2018 10:10       0      0       0       1       0       0
2062    7/3/2018 14:50       0      0       1       0       0       0
2063    7/3/2018 20:40       1      0       0       0       0       0
2064    7/3/2018 13:35       0      0       0       0       1       0
2065    7/3/2018 22:55       0      0       1       0       0       0
2066   7/3/2018 16.42        0      0       0       1       0       0
2067    7/3/2018 17.28       0      0       0       1       0       0
2068    7/3/2018 18:05       1      0       0       0       0       0
2069    7/3/2018 14:00       1      0       0       0       0       0
2070    7/3/2018 16:00       0      0       1       0       0       0
2071    7/3/2018 18:00       0      0       0       1       0       0
2072     7/3/2018 0:35       0      0       0       1       0       0
2073    7/3/2018 20:20       0      0       1       0       0       0
2074    7/3/2018 13:00       0      0       0       1       0       0
2075    7/3/2018 16:15       0      0       0       1       0       0
2076    7/3/2018 17:00       0      0       0       1       0       0
2077    7/3/2018 19:05       0      0       1       0       0       0
2078    7/3/2018 12:50       1      0       0       0       0       0
2079    7/3/2018 21:05       0      0       0       1       0       0
2080    7/3/2018 12:20       0      0       1       0       0       0
2081    7/3/2018 20:20       1      0       0       0       0       0
2082    7/3/2018 20:40       0      0       1       0       0       0
2083    7/3/2018 19:55       0      0       0       0       1       0
2084    7/3/2018 21:20       0      0       0       1       0       0
2085     7/3/2018 3:50       0      0       0       1       0       0
2086    7/3/2018 21:10       0      0       0       1       0       0
2087    7/3/2018 12:10       0      0       1       0       0       0
2088    7/3/2018 10:35       0      0       1       0       0       0
2089    7/3/2018 23:45       0      0       1       0       0       0

       latitude  longitude
0     22.737260  75.875987
1     22.720992  75.876083
2     22.736676  75.883168
3     22.746527  75.887139
4     22.769531  75.888772
5     22.735218  75.913366
6     22.736766  75.908579
7     22.736766  75.908579
8     22.722247  75.915294
9     22.722247  75.915294
10    22.741662  75.869137
11    22.741662  75.869137
12    22.746877  75.883168
13    22.744534  75.931421
14    22.765772  75.870461
15    22.767806  75.875984
16    22.715210  75.870047
17    22.698342  75.910757
18    22.694114  75.904223
19    22.711535  75.860105
20    22.715121  75.856601
21    22.719961  75.843657
22    22.719961  75.843657
23    22.727249  75.853214
24    22.726920  75.851580
25    22.726920  75.851580
26    22.726920  75.851580
27    22.723873  75.828416
28    22.723873  75.828416
29    22.723873  75.828416
...         ...        ...
2060  22.706070  75.860504
2061  22.714156  75.856339
2062  22.726750  75.881079
2063  22.721868  75.874134
2064  22.721040  75.903652
2065  22.729645  75.897313
2066  22.813268  75.848615
2067  22.745585  75.860658
2068  22.744118  75.894023
2069  22.792347  75.907511
2070  22.792347  75.907511
2071  22.741773  75.923824
2072  22.741773  75.923824
2073  22.728835  75.879600
2074  22.771026  75.851612
2075  22.707853  75.860957
2076  22.707853  75.860957
2077  22.710027  75.862469
2078  22.683873  75.879972
2079  22.673236  75.874455
2080  22.714573  75.846375
2081  22.707243  75.842508
2082  22.713983  75.841481
2083  22.709760  75.830908
2084  22.708832  75.828798
2085  22.712970  75.823580
2086  22.693481  75.821483
2087  22.531931  75.769126
2088  22.719569  75.857726
2089  22.686437  76.032055

[2090 rows x 9 columns]